### ISSUE TITLE
It seems to run the request twice

### ISSUE THREAD

**Issue by TJM** [bu/gin-method-override#1]
When I added this, it works, but it seems to run the method twice according to the logs (and database) :)

I slightly modified from your example in README.md:

`main.go`:

```go
package main

import (
	method "github.com/bu/gin-method-override"
	gin "github.com/gin-gonic/gin"
)

func main() {
	// create a Gin engine
	r := gin.Default()
	r.LoadHTMLFiles("form.html")

	// our middle-ware
	r.Use(method.ProcessMethodOverride(r))

	// routes
	r.PUT("/test", func(c *gin.Context) {
		c.String(200, "1")
	})
	r.GET("/", func(c *gin.Context) {
		c.HTML(200, "form.html", gin.H{})
	})

	// listen to request
	r.Run(":8080")
}
```

`form.html`: (same as example)

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <form action="/test" method="POST"> <!-- form method rewrite only works with POST request -->
        <input type="hidden" name="_method" value="PUT">
        <input type="text" name="testing" value="1">
        <button type="submit">Send</button>
    </form>
</body>
</html>
```

The output is: `11` instead of the expected `1` and I also see the line twice in the logs:

```log
$ go run main.go 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] PUT    /test                     --> main.main.func1 (4 handlers)
[GIN-debug] GET    /                         --> main.main.func2 (4 handlers)
[GIN-debug] Listening and serving HTTP on :8080



[GIN] 2021/01/06 - 21:12:36 | 200 |     285.465µs |             ::1 | GET      "/"
[GIN] 2021/01/06 - 21:12:45 | 200 |       5.609µs |             ::1 | PUT      "/test"
[GIN] 2021/01/06 - 21:12:45 | 200 |      70.195µs |             ::1 | PUT      "/test"
```

**Comment by bu** [comment]
Hi Tommy, just received this issue. Will look into it.

**Comment by TJM** [comment]
I was wondering if it should just return instead of running handle context? (shrug)

**Comment by bu** [comment]
@TJM just update middleware.go and it should works as expected.

I tried just `return` but it falls to original POST request. 
That's why we need to handleContext again there.

After few tries, it turns out to avoid request twice, we need to abort the current request first. 
Then, dispatch our new request to engine.

`master` version should fix your issues, please go get -u to update it and try!

**Comment by TJM** [comment]
```
[tmcneely@local gin-method-override] $ go test
go: downloading github.com/stretchr/testify v1.4.0
go: downloading golang.org/x/sys v0.0.0-20200116001909-b77594299b42
go: downloading github.com/ugorji/go v1.1.7
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/golang/protobuf v1.3.3
go: downloading github.com/go-playground/validator/v10 v10.2.0
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/leodido/go-urn v1.2.0
[GIN] 2021/01/06 - 22:06:38 | 200 |      59.801µs |                 | POST     "/test"
[GIN] 2021/01/06 - 22:06:38 | 200 |      13.906µs |                 | PUT      "/test"
[GIN] 2021/01/06 - 22:06:38 | 200 |      34.867µs |                 | PUT      "/test"
PASS
ok  	github.com/bu/gin-method-override	0.015s
[tmcneely@local gin-method-override] $
```

**Comment by TJM** [comment]
It is still logging the request twice, but it does appear to only be running it once. Interesting

**Comment by bu** [comment]
Yeah, this is logical that it receive POST first and then re-dispatch to PUT.
But it be less confusing if we can make it show only one record.

I will look into logging middleware and see what's can we do.

**Comment by TJM** [comment]
Thank you soo much for the lighting fast response and fix. The log thing is *very* low priority, I was just reporting it. Thanks!

**Comment by bu** [comment]
@TJM I just opened an issue (#2) to record this improvement. New progress will be reported there.

I will close this as it is solved.

**Comment by akhy** [comment]
This is because logging middleware is used BEFORE the method-overwrite. To fix, you should change the order to use method-overwrite FIRST. If you take a look at `gin.Default()`, it's already using both logging and recover middlewares, you should change to `gin.New()` and set the order by yourself.

Before:

```go
r := gin.Default()
r.Use(method.ProcessMethodOverride(r))
```

After:

```go
r := gin.New()
r.Use(method.ProcessMethodOverride(r))
r.Use(gin.Logger())
r.Use(gin.Recovery())
```

**Comment by TJM** [comment]
Thanks!

**Comment by bu** [comment]
Yeah this should fix this issue! Thanks  @akhy
